// Code generated by go-swagger; DO NOT EDIT.

// Package restapi api
//
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /v1
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
