openapi: 3.0.0
info:
  title: api
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /users/{userId}:
    get:
      description: Retrieve the information of the user with the matching user ID.
      operationId: get-users-userId
      parameters:
      - description: Id of an existing user.
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User Found
        "404":
          description: User Not Found
      summary: Get User Info by User ID
      tags: []
components:
  schemas:
    User:
      example:
        backgroundImagePath: backgroundImagePath
        updated_at: updated_at
        iconImagePath: iconImagePath
        profile: profile
        created_at: created_at
        id: id
        display_name: display_name
        deleted_at: deleted_at
        email: email
      properties:
        id:
          type: string
        display_name:
          type: string
        iconImagePath:
          type: string
        backgroundImagePath:
          type: string
        profile:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
      required:
      - backgroundImagePath
      - created_at
      - display_name
      - email
      - iconImagePath
      - id
      - profile
      - updated_at
      title: User
      type: object
      x-stoplight:
        id: dzs7bc8277r6i
    GetUserResponse:
      example:
        user:
          backgroundImagePath: backgroundImagePath
          updated_at: updated_at
          iconImagePath: iconImagePath
          profile: profile
          created_at: created_at
          id: id
          display_name: display_name
          deleted_at: deleted_at
          email: email
      properties:
        user:
          $ref: '#/components/schemas/User'
      required:
      - user
      title: GetUserResponse
      type: object
x-stoplight:
  id: 6km5rau3tev5g
